### ISSUE TITLE
Getting the time until the restaurant's closing time

### ISSUE THREAD

**Issue by tomerb15** [wix/wix-restaurants-js-sdk#4]
I was wondering what will be the best approach for getting the duration between any moment and the restaurant closing time.

Motivational is to let users in the process of ordering that there is less than 15min before closing time....

**Comment by dleshem** [comment]
For anything related to time availability, you can use https://github.com/wix/availability4js. Documentation is a bit lacking, but you can use the comprehensive tests as a living spec.

If you refer to the restaurant's open hour, simply create an ```AvailabilityIterator``` on ```Restaurant.openTimes```. The iterator is initialized with a moment in time, either "now" or any other given time. You can then iterate using ```hasNext``` and ```next``` and look for the next window with status ```unavailable```

Things get a bit more complicated for online ordering due to edge cases related to delivery areas / pickup times. For example, one delivery area may close while a second area is still available. You can use ```DisjunctiveAvailabilityIterator``` and ```ConjunctiveTimeWindowsIterator``` to perform logical operations on availability objects, for example to check that the restaurant is open, *and* that a certain delivery area is open.
